version: '3.4'
services:
  nginx:
    build: ./nginx
    ports:
      - ${INTERFACE}:80:80
      - ${INTERFACE}:443:433
    volumes:
      - ${APP_PATH}:/var/www/app
    restart: unless-stopped
    tty: true
    networks:
      - app-network
  php:
    build:
      context: ./php
      args:
        USER_ID: ${UID}
    ports:
      - ${INTERFACE}:9000:9000
    volumes:
      - ${APP_PATH}:/var/www/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - nginx
    environment:
      XDEBUG_CONFIG: "client_host=${INTERFACE}"
    restart: always
    networks:
      - app-network
  mysql:
    build: ./mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    tty: true
    ports:
      - ${INTERFACE}:3306:3306
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}/24